name: Controllo Concorsi Playwright

on:
  schedule:
    - cron: '0 7 * * *' # Alle 8:00 italiane
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa dipendenze
        run: |
          pip install requests playwright
          playwright install chromium --with-deps

      - name: Esegui lo script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py
